"""
Django settings for spiddjango project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from django.conf import settings

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1'
DEFAULT_ATTRIBUTE_CONSUMING_SERVICE = '1'
SPID_METADATA_DIR = getattr(settings, 'SPID_METADATA_DIR', None)
SAML_ATTRIBUTE_MAPPING = getattr(settings, 'SAML_ATTRIBUTE_MAPPING', {
    "spidCode": ('spid_code',),
    "name": ('first_name',),
    "gender": ('gender',),
    "ivaCode": ('iva_code',),
    "placeOfBirth": ('place_of_birth',),
    "companyName": ('company_name',),
    "mobilePhone": ('mobile_phone',),
    "expirationDate": ('expiration_date',),
    "address": ('address',),
    "digitalAddress": ('digital_address',),
    "email": ('email',),
    "registeredOffice": ('registered_office',),
    "idCard": ('id_card',),
    "dateOfBirth": ('date_of_birth',),
    "countyOfBirth": ('county_of_birth',),
    "familyName": ('last_name',),
    "fiscalNumber": ('fiscal_number',),
})
